### ISSUE TITLE
ValueError in solver.py

### ISSUE THREAD

**Issue by VincentLiu3** [js05212/MXNet-for-CDL#2]
I ran cdl.py and had the following error:

Traceback (most recent call last):
  File "cdl.py", line 61, in <module>
    lr_scheduler=mx.misc.FactorScheduler(20000,0.1))
  File "/home/vliu/MXNet-for-CDL/autoencoder.py", line 176, in finetune
    0, n_iter, {}, False)
  File "/home/vliu/MXNet-for-CDL/solver.py", line 84, in solve
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd}
  File "/home/vliu/MXNet-for-CDL/solver.py", line 84, in <dictcomp>
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd}
  File "/home/vliu/.local/lib/python2.7/site-packages/mxnet/ndarray.py", line 238, in __bool__
    raise ValueError("The truth value of an NDArray with more than one element is ambiguous.")
**ValueError: The truth value of an NDArray with more than one element is ambiguous.**

So I modified line 84 in solver.py to:
update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd **is True**}

Then I had another error:
Traceback (most recent call last):
  File "cdl.py", line 61, in <module>
    lr_scheduler=mx.misc.FactorScheduler(20000,0.1))
  File "/home/vliu/MXNet-for-CDL/autoencoder.py", line 176, in finetune
    0, n_iter, {}, False)
  File "/home/vliu/MXNet-for-CDL/solver.py", line 134, in solve
    lambda_u, lambda_v, dir_save, True)
  File "/home/vliu/MXNet-for-CDL/BCD_one.py", line 22, in BCD_one
    idx_a = np.where(R[:,j]>0)[0].A1 
**AttributeError: 'numpy.ndarray' object has no attribute 'A1'**

Do you know how to fix this problem? Thank you so much!

**Comment by js05212** [comment]
Hi Vincent,

Thanks for reporting the issue. It is probably because of the numpy version. Deleting all A1 in BCD_one.py should fix the problem. For example replace 'idx_a = np.where(R[:,j]>0)[0].A1' with 'idx_a = np.where(R[:,j]>0)[0]'. I will revise BCD_one.py in github accordingly.

Best,
Hao

**Comment by VincentLiu3** [comment]
Thank you, Hao. It works now!

**Comment by js05212** [comment]
Awesome.
