### ISSUE TITLE
After running " python cdl.py" I have this problem

### ISSUE THREAD

**Issue by daicoolb** [js05212/MXNet-for-CDL#3]
Hi,After running " python cdl.py" I have this problem：
                Traceback (most recent call last):
                File "cdl.py", line 61, in 
                lr_scheduler=mx.misc.FactorScheduler(20000,0.1))
                File "/home/daicoolb/MXNet-for-CDL/autoencoder.py", line 175, in finetune
                0, n_iter, {}, False)
                File "/home/daicoolb/MXNet-for-CDL/solver.py", line 84, in solve
                update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_a rrays) if nd}
                File "/home/daicoolb/MXNet-for-CDL/solver.py", line 84, in 
                update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_a rrays) if nd}
                File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray.py", line 238, in _ bool_
                raise ValueError("The truth value of an NDArray with more than one element i s ambiguous.")
                ValueError: The truth value of an NDArray with more than one element is ambiguou s.

**Comment by nimit2894** [comment]
I am facing the same issue, and I would really appreciate the creator of this repo to respond to this, as it is quite hard to find out the source of this error from the huge ndarray.py file that has been created in mxnet

**Comment by js05212** [comment]
Hi, sorry for the late reply. I think this is because you are using a newer version of MXNet. There might be some compatibility issue in here. Have you try using earlier version of MXNet?

**Comment by xanhho** [comment]
Hi, I also have the same error when I running cdl.py
INFO:root:Fine tuning...
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "autoencoder.py", line 175, in finetune
    return U, V, theta, BCD_loss
  File "solver.py", line 84, in solve
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd}
  File "solver.py", line 84, in <dictcomp>
    update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd}
  File "/home/xanhho/.local/lib/python2.7/site-packages/mxnet/ndarray.py", line 293, in __bool__
    raise ValueError("The truth value of an NDArray is ambiguous. " \
ValueError: The truth value of an NDArray is ambiguous. Please convert to number with asscalar() first.

Can you guide me how to fix it?

**Comment by js05212** [comment]
Hi, might I ask what version of MXNet you are using?

**Comment by xanhho** [comment]
Thank you for your reply!
I had fixed this error by install another version of MXNet.
I have some question related to your code. Could you please answer for me?
In the paper had mentioned 5 hyperparameters lambda_w, lambda_n, lambda_u, lambda_s, lambda_v.  But I see you just mentioned lambda_u and lambda_v in your code? How about lambda_w, lambda_n, lambda_s?
Is there any related between lv,  lambda_v_rt (in your code) and lambda_w, lambda_n, lambda_s (in the paper)?

Thank you very much!

**Comment by js05212** [comment]
Hi. lambda_w is equivalent to the weight decay coefficient in NN if we use MAP inference, and it is fixed to 1e-4 (since the performance is not sensitive to it). lambda_s can be taken to positive infinity as mentioned in the paper. Essentially what is important is the ratio lambda_n/lambda_v and lambda_u.

Hope this helps!

**Comment by xanhho** [comment]
Hi, thank you for your reply!

Is this code can reproduce the result as mentioned in the paper? Or it just a simple version for CDL?

**Comment by js05212** [comment]
Hi, it is a simple version for CDL. For the full version, please go to wanghao.in/code/cdl-release.rar.You are more than welcome to fork this repo to make it the full version though. Feel free to ask if you need help.

**Comment by xanhho** [comment]
Hi, thank you very much for your support!

**Comment by m2rik** [comment]
I am getting an error on line 34 (syntax error) can you help please ?

**Comment by m2rik** [comment]
hi, can i know which version of MXNet solved the problem ?

**Comment by xanhho** [comment]
Hi,
I am using MXNet 0.11.0.

**Comment by m2rik** [comment]
i'm using the same version still getting the same error ,any solution ?

**Comment by xanhho** [comment]
Can you show me the error?
Have you tried debug by python command?

**Comment by m2rik** [comment]
![error2](https://user-images.githubusercontent.com/26003054/31482010-dc26c600-af43-11e7-8953-35a3c5893152.PNG)

**Comment by xanhho** [comment]
You can fix this error by change the code in line 84 by this line: 
        # update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd}
        update_dict = {name: nd for name, nd in zip(sym.list_arguments(), exe.grad_arrays) if nd is not None}

**Comment by m2rik** [comment]
done that,now all i'm getting are indentation errors ,any way to fix them all at once ?
![error3](https://user-images.githubusercontent.com/26003054/31554499-650f2922-b05b-11e7-88ad-d98e4a8db05e.PNG)

**Comment by m2rik** [comment]
Okay,all the errors were just the Python version issue .Now stuck on the show recommendations file with the error **attribute error object has no attribute 'A1'** .can anyone solve this 
![error4](https://user-images.githubusercontent.com/26003054/31583927-94470a7c-b1c1-11e7-9f24-c459b90226fb.PNG)

**Comment by xanhho** [comment]
Change by these following lines, it will work.
// s_test = set(np.where(R_test[user_id,:]>0)[1].A1)
// l_train = np.where(R_train[user_id,:]>0)[1].A1.tolist()
s_test = set(np.ravel(np.where(R_test[user_id, :] > 0)[1]))
l_train = np.ravel(np.where(R_train[user_id, :] > 0)[1]).tolist()

**Comment by m2rik** [comment]
It worked, can you tell me how it fixes the A1 attribute of the array?

**Comment by js05212** [comment]
Thanks, @xanhxanh94, for your help!

**Comment by xanhho** [comment]
Hi, @js05212, 
You're welcome!
Can you please answer for me the questions in js05212/CDL?

Thank you very much for your support!

**Comment by ShuyaZhang** [comment]
Hi, @xanhxanh94 , I've corrected several mistakes you mentioned before, now I'm using earlier version of mxnet. However, I still have following error when running cdl.py, could you solve it? 
![image](https://user-images.githubusercontent.com/22425333/48121530-28b6f300-e2b0-11e8-9f1e-949255019101.png)

**Comment by MaurizioFD** [comment]
> 
> 
> Hi, @xanhxanh94 , I've corrected several mistakes you mentioned before, now I'm using earlier version of mxnet. However, I still have following error when running cdl.py, could you solve it?
> ![image](https://user-images.githubusercontent.com/22425333/48121530-28b6f300-e2b0-11e8-9f1e-949255019101.png)

The error is due to the fact that in python 3 the .values() function returns a view.

You can solve it by creating a list with the dict_values object. The code in solver.py in lines 131-138 becomes:

```
theta = list(model.extract_feature(sym[0], args, auxs,
	data_iter, X.shape[0], xpu).values())[0]
# update U, V and get BCD loss
U, V, BCD_loss = BCD_one(R, U, V, theta,
	lambda_u, lambda_v, dir_save, True)
# get recon' loss
Y = list(model.extract_feature(sym[1], args, auxs,
	data_iter, X.shape[0], xpu).values())[0]

```
