### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by PatelAxita** [js05212/MXNet-for-CDL#8]
p4: lambda_v/lambda_u/ratio/K: 10.000000/1.000000/0.010000/50
Traceback (most recent call last):
  File "cdl.py", line 32, in <module>
    X = data.get_mult()
  File "/home/axita/Downloads/MXNet-for-CDL-master/data.py", line 5, in get_mult
    X = read_mult('mult.dat',8000).astype(np.float32)
  File "/home/axita/Downloads/MXNet-for-CDL-master/mult.py", line 13, in read_mult
    X = (X.T/arr_max).T
MemoryError

**Comment by m2rik** [comment]
Hey,axita could you contact me - m2rikforyou@gmail.com
